language: java
script: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
sudo: false
jdk:
  - oraclejdk7
  - oraclejdk8
notifications:
  slack:
    rooms:
      - projectkorra:h9WFZqQ2o6fuCkI69ko28XgF#general
      - projectkorra:h9WFZqQ2o6fuCkI69ko28XgF#development
